name: 04 - Using Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing folders
              run: ls
        #0. checout the code from the repository
        #1. Install dependencies of our reat app
        #2. Execute automated tests
        
